[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'greymd/oscyank.vim'

[[plugins]]
repo = 'haya14busa/vim-poweryank'


[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tomtom/tcomment_vim'
